title: Rickey K. Liang
photo: /assets/img/photo.jpg
description: This is the personal homepage of Kunchangtai Liang.
show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
cv_link: /lkct_CV.pdf
cv_zh_link: /lkct_CV_zh.pdf
email: mailto:liangkunchangtaihsfx_at_126.com
