title: Rickey K. Liang
photo: /assets/img/photo.jpg
description: This is the personal homepage of Kunchangtai Liang.
show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
cv_link: /lkct_CV.pdf
email: mailto:K.Liang-4_at_sms.ed.ac.uk
