title: KCT Liang's Homepage
photo: /assets/img/photo.jpg
description: <strong>Kunchangtai Liang</strong>Undergraduate of EECS, PKU
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
cv_link: /lkct_CV.pdf
email: lkct@pku.edu.cn
