title: Rickey K. Liang
photo: /assets/img/photo.jpg
description: This is the personal homepage of Kunchangtai (Rickey) Liang.
show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal

cv_link: /CV_RLiang.pdf
cv_zh_link: /lkct_CV_zh.pdf
email: mailto:liang_at_cs.uni-saarland.de
